const LEARNING_KEYWORDS = [
  'learn',
  'study',
  'skill',
  'course',
  'quiz',
  'question',
  'answer',
  'doubt',
  'mentor',
  'session',
  'assignment',
  'roadmap',
  'level',
  'beginner',
  'intermediate',
  'salesforce',
  'crm',
  'platform fundamentals',
  'object',
  'objects',
  'field',
  'fields',
  'relationship',
  'relationships',
  'record',
  'records',
  'apex',
  'flow',
  'flows',
  'automation',
  'lwc',
  'admin',
  'permission set',
  'permission set group',
  'profile',
  'role hierarchy',
  'sharing rule',
  'org-wide default',
  'org wide default',
  'owd',
  'field-level security',
  'field level security',
  'fls',
  'validation rule',
  'report',
  'reports',
  'dashboard',
  'dashboards',
  'data import',
  'data export',
  'app builder',
  'page layout',
  'soql',
  'sosl',
  'dml',
  'trigger',
  'trigger framework',
  'batch apex',
  'queueable apex',
  'scheduled apex',
  'exception handling',
  'test class',
  'code coverage',
  'governor limit',
  'html',
  'css',
  'wire adapter',
  'decorator',
  'decorators',
  'custom event',
  'lightning data service',
  'lds',
  'toast',
  'navigation',
  'lifecycle hook',
  'data cloud',
  'data stream',
  'data ingestion',
  'data lake object',
  'dlo',
  'data model object',
  'dmo',
  'identity resolution',
  'calculated insight',
  'segmentation',
  'activation target',
  'sales cloud',
  'service cloud',
  'marketing cloud',
  'experience cloud',
  'commerce cloud',
  'agentforce',
  'agent builder',
  'prompt template',
  'grounding',
  'trailhead',
  'sap',
  's/4hana',
  'erp',
  'fico',
  'sap fico',
  'sap mm',
  'sap sd',
  'sap hcm',
  'sap pp',
  'abap',
  'master data',
  'transaction code',
  'tcode',
  'pmp',
  'project management',
  'project lifecycle',
  'project initiation',
  'scope management',
  'schedule management',
  'cost management',
  'risk management',
  'stakeholder management',
  'resource management',
  'communication management',
  'quality management',
  'agile',
  'scrum',
  'hybrid',
  'monitoring and control',
  'project closure',
  'web development',
  'javascript',
  'python',
  'data',
  'soft skill',
  'interview',
  'career',
  'onboarding',
  'coding',
  'code',
  'yes',
  'yeah',
  'ok',
  'okay',
  'ready',
  'start',
  'new to coding',
  'test my level',
  'reset',
  'start over',
  'new topic',
  'clear context',
];

/**
 * @param {string} text
 * @returns {boolean}
 */
export function isLearningRelated(text) {
  const normalizedText = text.toLowerCase();
  return LEARNING_KEYWORDS.some((keyword) => normalizedText.includes(keyword));
}

/**
 * @returns {string}
 */
export function buildOutOfScopeMessage() {
  return (
    'I can help only with learning, upskilling, session preparation, quizzes, assignments, and mentor support. ' +
    'Please ask me about a course topic such as Salesforce, Apex, SAP, PMP, web development, data skills, soft skills, or interview prep.'
  );
}
